### ISSUE TITLE
[Bug] All GApps can't be downloaded 所有GApps均无法下载

### ISSUE THREAD

**Issue by Just-Prog** [LSPosed/MagiskOnWSALocal#357]
### Steps to reproduce/复现步骤

Choose any option listed in `Which GApps do you want to install?` menu, then start building process.

在选择GApps的菜单任选一个选项，随后开始构建。

### Expected behaviour/预期行为

Download GApps files successfully.

成功下载 GApps 的文件。

### Actual behaviour/实际行为

1. When choose `MindTheGapps`, I got the following error outputs. 选 `MindTheGapps` 的时候报错如下: 

```
Generating MindTheGapps download link: arch=x64 variant=pico
Traceback (most recent call last):
  File "/home/prog/MagiskOnWSALocal/scripts/generateGappsLink.py", line 58, in <module>
    link = re.search(f'https://.*{release}.*{abi_map[arch]}.*\.zip/download', res.text).group().replace(
AttributeError: 'NoneType' object has no attribute 'group'
Build: an error has occurred, exit
```

2. When choose `OpenGApps`, I got invalid response from SourceForge. 如果选 `OpenGApps` 的话服务器会报错:

```
01/19 20:44:05 [ERROR] CUID#11 - Download aborted. URI=https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 未找到资源
```

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

dc7083ccface4eac389bbeff4b3aad049116c888

### Linux distribution info/Linux 发行版信息

```
prog@Windows-11:~/MagiskOnWSALocal$ uname -a
Linux Windows-11 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Windows version/Windows 版本

10.0.22621.1105

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver canary --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: canary
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>MindTheGapps</summary>

```
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
WSA Version=2210.40000.7.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1674133354&P2=404&P3=2&P4=VvQrdex%2fgvYFMaE7m6KEYaNtbJWQc1MkAsK0bANd4xMhvYJ3vWVB5jXnnis0nKWAZi6Z%2b58Sz%2bG4whM%2fzlaU3A%3d%3d to /home/prog/MagiskOnWSALocal/download/Microsoft.UI.Xaml_x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/15af34f3-b0f6-42bb-9e95-19888b0c545c?P1=1674161072&P2=404&P3=2&P4=N5r3Sf20xOXZZCibcKODjMYDPYssdi%2bGdWKGxnh0syu9gM0rNClt8e1sggS6ZL6ZNNthPxRcSU%2b82N2AtTmQ%2bA%3d%3d to /home/prog/MagiskOnWSALocal/download/wsa-retail.zip
Generating Magisk download link: release type=canary
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@5b2934603f979d7133e67bbc30c6ce3fa0d8e31e/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
Traceback (most recent call last):
  File "/home/prog/MagiskOnWSALocal/scripts/generateGappsLink.py", line 58, in <module>
    link = re.search(f'https://.*{release}.*{abi_map[arch]}.*\.zip/download', res.text).group().replace(
AttributeError: 'NoneType' object has no attribute 'group'
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Download Directory
```

</details>

<details>
<summary>OpenGApps</summary>

```
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
WSA Version=2210.40000.7.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1674132914&P2=404&P3=2&P4=QEN4uGZo0WjyCrF3IeRlZLzEIW0Mnf2wOR38dZOvat03%2b0%2fZKCAFQGGSXyf2GTIYelC1rFswlF%2bi0A1hOzbcuA%3d%3d to /home/prog/MagiskOnWSALocal/download/Microsoft.UI.Xaml_x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/15af34f3-b0f6-42bb-9e95-19888b0c545c?P1=1674160601&P2=404&P3=2&P4=IVBSzL2XvPQ5XBTQGPQ0VHz8Ard%2b92Ar2WtV87wixOFccYK5hX38oQQwyroM%2buMosc4Wtk6x82tHYk%2bSmUVkzQ%3d%3d to /home/prog/MagiskOnWSALocal/download/wsa-retail.zip
Generating Magisk download link: release type=canary
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@5b2934603f979d7133e67bbc30c6ce3fa0d8e31e/app-release.apk
Generating OpenGApps download link: arch=x64 variant=pico
DATE=20220503
download link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Download Artifacts
解析环境变量“all_proxy”时捕捉到错误
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--all-proxy'.
  -> [OptionHandlerImpl.cc:520] errorCode=1 unrecognized proxy format


01/19 20:44:04 [NOTICE] Downloading 5 item(s)

01/19 20:44:04 [NOTICE] GID#b38d2c9be839b642 - 下载已完成：/home/prog/MagiskOnWSALocal/download/Microsoft.UI.Xaml_x64.appx

01/19 20:44:04 [NOTICE] 下载已完成：/home/prog/MagiskOnWSALocal/download/Microsoft.UI.Xaml_x64.appx
[DL:285KiB][#1ecdfd 0B/0B][#f194b6 32KiB/1.3GiB(0%)][#b020bd 0B/0B][#ae51ac 0B/0B]
01/19 20:44:05 [NOTICE] GID#b020bd89f2d64251 - 下载已完成：/home/prog/MagiskOnWSALocal/download/magisk-canary.zip

01/19 20:44:05 [NOTICE] 下载已完成：/home/prog/MagiskOnWSALocal/download/magisk-canary.zip

01/19 20:44:05 [ERROR] CUID#11 - Download aborted. URI=https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 未找到资源

01/19 20:44:05 [NOTICE] GID 为 ae51acfff9eca9a4 的下载项未完成：/home/prog/MagiskOnWSALocal/download/OpenGApps-x64-11.0-pico.zip

01/19 20:44:06 [NOTICE] CUID#7 - Redirecting to https://download.microsoft.com/download/4/7/c/47c6134b-d61f-4024-83bd-b9c9ea951c25/appx/Microsoft.VCLibs.x64.14.00.Desktop.appx
[DL:16MiB][#1ecdfd 0B/0B][#f194b6 53MiB/1.3GiB(3%)]
01/19 20:44:08 [NOTICE] GID#1ecdfd0ac9c42f37 - 下载已完成：/home/prog/MagiskOnWSALocal/download/Microsoft.VCLibs.x64.14.00.Desktop.appx

01/19 20:44:08 [NOTICE] 下载已完成：/home/prog/MagiskOnWSALocal/download/Microsoft.VCLibs.x64.14.00.Desktop.appx
 *** Download Progress Summary as of Thu Jan 19 20:45:04 2023 ***
=======================================================================================================================
[#f194b6 1.2GiB/1.3GiB(92%) CN:10 DL:22MiB ETA:4s]
FILE: /home/prog/MagiskOnWSALocal/download/wsa-retail.zip
-----------------------------------------------------------------------------------------------------------------------

[#f194b6 1.3GiB/1.3GiB(99%) CN:1 DL:13MiB]
01/19 20:45:13 [NOTICE] 下载已完成：/home/prog/MagiskOnWSALocal/download/wsa-retail.zip

下载结果：
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b38d2c|OK  |       0B/s|/home/prog/MagiskOnWSALocal/download/Microsoft.UI.Xaml_x64.appx
b020bd|OK  |       0B/s|/home/prog/MagiskOnWSALocal/download/magisk-canary.zip
ae51ac|ERR |       0B/s|/home/prog/MagiskOnWSALocal/download/OpenGApps-x64-11.0-pico.zip
1ecdfd|OK  |       0B/s|/home/prog/MagiskOnWSALocal/download/Microsoft.VCLibs.x64.14.00.Desktop.appx
f194b6|OK  |    20MiB/s|/home/prog/MagiskOnWSALocal/download/wsa-retail.zip

状态标识：
(OK): 下载完成。(ERR): 发生错误。

传输重启后 aria2 可继续该下载。
如见任何错误，详查日志文件。详细信息见帮助或手册页面中的“-l”选项。
We have encountered an error while downloading files.
```

</details>

**Comment by Just-Prog** [comment]
If I visit [Direct Download Link of OpenGApps_11_x86-64-pico](https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip) in browser, it redirects to [OpenGApps -  Browse Files at SourceForge.net](https://sourceforge.net/projects/opengapps/files/).

用浏览器打开 OpenGApps 的 [这个下载直链](https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip) 的话会重定向到 [OpenGApps -  Browse Files at SourceForge.net](https://sourceforge.net/projects/opengapps/files/)。

**Comment by Just-Prog** [comment]
As for MindTheGapps... It got nothing from SourceForge RSS in this script: `generateGappsLink.py`.

[This page](https://sourceforge.net/projects/wsa-mtg) also have nothing in its files tab.

至于 MindTheGapps …… 它完全没从 `generateGappsLink.py` 脚本里的的 SourceForge RSS 读到链接。

[这个项目的主页](https://sourceforge.net/projects/wsa-mtg) 的文件栏里什么也没有。

**Comment by s1204IT** [comment]
> @s1204IT MindTheGApps pre-build all folder disappeared, was it deleted? OpenGapps' Android 11 build disappeared I wonder if too much traffic caused sourceforge to delete the archive

I didn't delete it.

**Comment by s1204IT** [comment]
> > @s1204IT MindTheGApps pre-build all folder disappeared, was it deleted? OpenGapps' Android 11 build disappeared I wonder if too much traffic caused sourceforge to delete the archive
> 
> I didn't delete it.

Not sure why it was removed.

**Comment by Howard20181** [comment]
It looks like the whole sourceforge rolled back to 2021 and the other repositories 2022 data are missing, no announcement, waiting for recovery

**Comment by s1204IT** [comment]
https://github.com/s1204IT/MindTheGappsBuilder/releases/tag/20230119
Release from [MindTheGappsBuilder](https://github.com/s1204IT/MindTheGappsBuilder)

**Comment by s1204IT** [comment]
> https://github.com/s1204IT/MindTheGappsBuilder/releases/tag/20230119 Release from [MindTheGappsBuilder](https://github.com/s1204IT/MindTheGappsBuilder)

@Howard20181 
https://api.github.com/repos/s1204IT/MindTheGappsBuilder/releases/latest
Is this useful for link generation?

**Comment by Howard20181** [comment]
Should I implement the logic to get it from Github? Or should I wait for Sourceforge to fix it? I saw someone on Twitter as early as 2 hours ago complaining about the disappearance of 2022 and 2023 files from the entire site.

**Comment by s1204IT** [comment]
> Should I implement the logic to get it from Github?

Please implementing.

**Comment by Howard20181** [comment]
Done
Now when downloading MindTheGapps from SourceForge fails, it will try to download from Github

Please keep this issue open until SourceForge is restored

**Comment by Howard20181** [comment]
It looks like SourceForge has recovered
