### ISSUE TITLE
Ubuntu-22.04又一次报错

### ISSUE THREAD

**Issue by sst2020** [LSPosed/MagiskOnWSALocal#42]
ARCH=x64
RELEASE_TYPE=retail
MAGISK_VER=debug
GAPPS_VARIANT=pico
REMOVE_AMAZON=keep
ROOT_SOL=magisk
COMPRESS_OUTPUT=no
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1661477813&P2=404&P3=2&P4=kRq5ofBiwzOQkcXctbxzXHEZSAyXjuKT9yh7I0ZPhUfisBJW%2bMktfzbkQ71peRw8Ds34AA4tg5rlXdGioI%2fBjA%3d%3d to /root/MagiskOnWSALocal/download/xaml-x64.appx
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f079dcaa320>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fe3.delivery.mp.microsoft.com', port=443): Max retries exceeded with url: /ClientWebService/client.asmx/secured (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f079dcaa320>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MagiskOnWSALocal/scripts/generateWSALinks.py", line 98, in <module>
    out = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fe3.delivery.mp.microsoft.com', port=443): Max retries exceeded with url: /ClientWebService/client.asmx/secured (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f079dcaa320>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
An error has occurred, exit
Cleanup Work Directory
Cleanup Download Directory
已实践的方式：
1.改DNS
2.改IP

**Comment by Howard20181** [comment]
网络问题，挂代理再试
