### ISSUE TITLE
[Bug] Unzip WSA failed / Bad CRC-32

### ISSUE THREAD

**Issue by inxomnyaa** [LSPosed/MagiskOnWSALocal#756]
### Steps to reproduce/复现步骤

1. Fork script
2. Run

### Expected behaviour/预期行为

Unzip succeeds and WSA works

### Actual behaviour/实际行为

Unzip WSA failed with Bad CRC-32 error

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

d44a77be84fac312d343ac501b497828209da089

### Linux distribution info/Linux 发行版信息

WSL2
Ubuntu 20.04.6 LTS

### Windows version/Windows 版本

10.0.19045.3803

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand none --remove-amazon

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand none --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: none
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2310.40000.2.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/28edaebf-8019-4844-ba32-8ab019bc9391?P1=1703441597&P2=404&P3=2&P4=aTte930GFs3PeYmsuELY98SrdSst0q6i8ksfO2RL%2b0DVW8xKSv4SvYRgTzkLGIWGZ7yPpumGYRAD4Zhl1t2vjA%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/251bbb12-dbfc-4820-b0ff-c4dfa70ffb09?P1=1703441666&P2=404&P3=2&P4=jdQ%2bGB5eS9nmig6NUyy%2fLSXdtFcZFBB8L%2bkMupucvbcc8vKyzchRNnXTYjnvsx%2bpbtTQrC2BJd0iBwVZyfj3XA%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/f2b59894-efdf-4dde-8b2c-23012b4b3cf6?P1=1703469734&P2=404&P3=2&P4=gzBBtY%2bMPO810GwQLkDybRKusWqD5df5lnGKvnk6ZqD7YHam4sCV9RTgLK43sZRgPkyzDpSoSYnVrSsYU6LDDQ%3d%3d
path: ../download/wsa-retail.zip

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/986a8270-404c-4470-871d-5c4090dcaa79?P1=1703441735&P2=404&P3=2&P4=mh9ppt5KMS44QwQg9AbYFKbdWosXr2QXWfGPIH8gXy96X96fwyIDb%2fwNFIUTDxt4fDRERtVUbyfAY%2b6WyGDxXA%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

Download Artifacts

12/24 19:03:18 [NOTICE] Downloading 4 item(s)

12/24 19:03:18 [NOTICE] GID#c9e57fc28fdacce2 - Download has already completed: ../download/Microsoft.VCLibs.140.00_x64.appx

12/24 19:03:18 [NOTICE] GID#f3f42f3ca3e5f733 - Download has already completed: ../download/Microsoft.UI.Xaml.2.8_x64.appx

12/24 19:03:18 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx

12/24 19:03:18 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx

12/24 19:03:18 [NOTICE] GID#1510e68e2e45cfb4 - Download has already completed: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

12/24 19:03:18 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
 *** Download Progress Summary as of Sun Dec 24 19:04:19 2023 ***
======================================================================================================================================================================================
[#51caf3 147MiB/1.3GiB(10%) CN:16 DL:2.3MiB ETA:9m4s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:05:20 2023 ***
======================================================================================================================================================================================
[#51caf3 311MiB/1.3GiB(22%) CN:16 DL:3.0MiB ETA:6m]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:06:20 2023 ***
======================================================================================================================================================================================
[#51caf3 484MiB/1.3GiB(34%) CN:16 DL:3.5MiB ETA:4m22s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:07:21 2023 ***
======================================================================================================================================================================================
[#51caf3 666MiB/1.3GiB(47%) CN:16 DL:2.9MiB ETA:4m14s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:08:22 2023 ***
======================================================================================================================================================================================
[#51caf3 807MiB/1.3GiB(57%) CN:16 DL:2.3MiB ETA:4m16s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:09:23 2023 ***
======================================================================================================================================================================================
[#51caf3 895MiB/1.3GiB(63%) CN:16 DL:1.0MiB ETA:7m45s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:10:24 2023 ***
======================================================================================================================================================================================
[#51caf3 1.0GiB/1.3GiB(73%) CN:16 DL:2.6MiB ETA:2m19s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:11:24 2023 ***
======================================================================================================================================================================================
[#51caf3 1.1GiB/1.3GiB(80%) CN:16 DL:853KiB ETA:5m34s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:12:25 2023 ***
======================================================================================================================================================================================
[#51caf3 1.1GiB/1.3GiB(86%) CN:15 DL:1.5MiB ETA:1m57s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Sun Dec 24 19:13:26 2023 ***
======================================================================================================================================================================================
[#51caf3 1.2GiB/1.3GiB(94%) CN:3 DL:2.1MiB ETA:36s]
FILE: ../download/wsa-retail.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[#51caf3 1.3GiB/1.3GiB(99%) CN:4 DL:2.2MiB]
12/24 19:14:00 [NOTICE] Download complete: ../download/wsa-retail.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c9e57f|OK  |       0B/s|../download/Microsoft.VCLibs.140.00_x64.appx
f3f42f|OK  |       0B/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
1510e6|OK  |       0B/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
51caf3|OK  |   2.1MiB/s|../download/wsa-retail.zip

Status Legend:
(OK):download completed.
Extract WSA
unzipping WsaPackage_2310.40000.2.0_x64_Release-Nightly.msix to /tmp/wsa-build-j3Kct1HChg_/wsa
Traceback (most recent call last):
  File "extractWSA.py", line 81, in <module>
    zip_path = zip.extract(f, workdir)
  File "/usr/lib/python3.8/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.8/zipfile.py", line 1702, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python3.8/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/usr/lib/python3.8/zipfile.py", line 1030, in _read1
    self._update_crc(data)
  File "/usr/lib/python3.8/zipfile.py", line 958, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'WsaPackage_2310.40000.2.0_x64_Release-Nightly.msix'
ERROR: Unzip WSA failed, is the download incomplete?
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Download Directory
```
[//]: <> (Don't modify below)
</details>

**Comment by MustardChef** [comment]
@inxomnyaa 
Follow: https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Fix%20Guides/Pre-Install%20Issues/Extraction%20Errors.md

**Comment by yujincheng08** [comment]
Downloading issue. Please retry.
