### ISSUE TITLE
[Bug] build was unsuccessful

### ISSUE THREAD

**Issue by HuskeyDev** [LSPosed/MagiskOnWSALocal#799]
### Steps to reproduce/复现步骤

1. git clone https://github.com/LSPosed/MagiskOnWSALocal.git --depth 1
2. ./scripts/run.sh
3. Follow the steps

### Expected behaviour/预期行为

Generate the MagiskOnWSALocal installer

### Actual behaviour/实际行为

```shell
COMMAND_LINE=--arch x64 --release-type RP --root-sol magisk --magisk-ver canary --install-gapps --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: canary
INFO: Root Solution: magisk
INFO: Compress Format: 7z
INFO: Release Name: Release Preview

Generating WSA Download Links
Generating WSA download link: arch=x64 release_type=Release Preview

WSA Build Version=2311.40000.5.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/c452d4ef-2486-4efe-9c99-36b3d23e0160?P1=1721142520&P2=404&P3=2&P4=crwlFu%2fU3Cb4iZuBgFZ0hWo19T5Iw9mNkygx2SX%2fl618VOHPR6AetOQo%2f%2fu0DeTXOkMRhaPvOKqI7As0EC34YA%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/251bbb12-dbfc-4820-b0ff-c4dfa70ffb09?P1=1721142591&P2=404&P3=2&P4=XmZhadTHcDrjvgyX1I512XsDu5P5BEQQOfWDOHiO34QKlSCYGI8yJ3uz2OV%2f6g0WCCq5znHbuFqU%2bWHiShcYvw%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/9f21fa47-fe2c-4f89-804e-e2b697f0bb14?P1=1721170589&P2=404&P3=2&P4=f%2bcMJsYuGE7S03KMNaPmyD0BsqxsAuB6HfjyHt8efpIiUzk5iyHd3d6%2fqCSFrOydWy0206loYPabUshI25WfQw%3d%3d
path: ../download/wsa-RP.zip

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/27ca12bc-f81d-45ff-95d0-12ad79f15735?P1=1721142611&P2=404&P3=2&P4=kGVu6yxJnXyVlDEJPEZa8YEIl160F8zWkf%2brppk2TuC4KK4%2b5If9lNqMEep4XFAOVogn7EDjt71zkrY3Krgdbg%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

Downloading WSA

07/16 22:58:57 [NOTICE] Downloading 4 item(s)

07/16 22:58:57 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx
[DL:21MiB][#d9caa7 2.7MiB/4.8MiB(56%)][#11a874 61MiB/1.3GiB(4%)][#9f444b 5.5MiB/6.4MiB(85%)]
07/16 22:59:01 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
[DL:21MiB][#d9caa7 4.7MiB/4.8MiB(96%)][#11a874 101MiB/1.3GiB(7%)]
07/16 22:59:03 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx
 *** Download Progress Summary as of Tue Jul 16 22:59:58 2024 ***
===========================================================================================================
[#11a874 1.2GiB/1.3GiB(94%) CN:7 DL:22MiB ETA:3s]
FILE: ../download/wsa-RP.zip
-----------------------------------------------------------------------------------------------------------

[#11a874 1.3GiB/1.3GiB(99%) CN:1 DL:16MiB]
07/16 23:00:04 [NOTICE] Download complete: ../download/wsa-RP.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0c3bd8|OK  |   3.1MiB/s|../download/Microsoft.VCLibs.140.00_x64.appx
9f444b|OK  |   1.7MiB/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
d9caa7|OK  |   904KiB/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
11a874|OK  |    21MiB/s|../download/wsa-RP.zip

Status Legend:
(OK):download completed.
Extracting WSA
unzipping WsaPackage_2311.40000.5.0_x64_Release-Nightly.msix to /tmp/wsa-build-j66X4cNgrT_/wsa
 unzipping from /tmp/wsa-build-j66X4cNgrT_/wsa/WsaPackage_2311.40000.5.0_x64_Release-Nightly.msix
done

Generating Download Links
Generating Magisk download link: release type=canary
Failed to fetch from GitHub API, fallbacking to jsdelivr...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/LSPosed/WSA-Addon/releases/latest (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generateMagiskLink.py", line 64, in <module>
    res = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/LSPosed/WSA-Addon/releases/latest (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Download Directory
``` 

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

2d2c7905f5e7bbbe288b4d8f82e8911e5cb2df6f

### Linux distribution info/Linux 发行版信息

20.04LTS

### Windows version/Windows 版本

19045.4651

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type RP --root-sol magisk --magisk-ver canary --install-gapps --compress-format 7z

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
COMMAND_LINE=--arch x64 --release-type RP --root-sol magisk --magisk-ver canary --install-gapps --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: canary
INFO: Root Solution: magisk
INFO: Compress Format: 7z
INFO: Release Name: Release Preview

Generating WSA Download Links
Generating WSA download link: arch=x64 release_type=Release Preview

WSA Build Version=2311.40000.5.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/c452d4ef-2486-4efe-9c99-36b3d23e0160?P1=1721142520&P2=404&P3=2&P4=crwlFu%2fU3Cb4iZuBgFZ0hWo19T5Iw9mNkygx2SX%2fl618VOHPR6AetOQo%2f%2fu0DeTXOkMRhaPvOKqI7As0EC34YA%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/251bbb12-dbfc-4820-b0ff-c4dfa70ffb09?P1=1721142591&P2=404&P3=2&P4=XmZhadTHcDrjvgyX1I512XsDu5P5BEQQOfWDOHiO34QKlSCYGI8yJ3uz2OV%2f6g0WCCq5znHbuFqU%2bWHiShcYvw%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/9f21fa47-fe2c-4f89-804e-e2b697f0bb14?P1=1721170589&P2=404&P3=2&P4=f%2bcMJsYuGE7S03KMNaPmyD0BsqxsAuB6HfjyHt8efpIiUzk5iyHd3d6%2fqCSFrOydWy0206loYPabUshI25WfQw%3d%3d
path: ../download/wsa-RP.zip

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/27ca12bc-f81d-45ff-95d0-12ad79f15735?P1=1721142611&P2=404&P3=2&P4=kGVu6yxJnXyVlDEJPEZa8YEIl160F8zWkf%2brppk2TuC4KK4%2b5If9lNqMEep4XFAOVogn7EDjt71zkrY3Krgdbg%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

Downloading WSA

07/16 22:58:57 [NOTICE] Downloading 4 item(s)

07/16 22:58:57 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx
[DL:21MiB][#d9caa7 2.7MiB/4.8MiB(56%)][#11a874 61MiB/1.3GiB(4%)][#9f444b 5.5MiB/6.4MiB(85%)]
07/16 22:59:01 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
[DL:21MiB][#d9caa7 4.7MiB/4.8MiB(96%)][#11a874 101MiB/1.3GiB(7%)]
07/16 22:59:03 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx
 *** Download Progress Summary as of Tue Jul 16 22:59:58 2024 ***
===========================================================================================================
[#11a874 1.2GiB/1.3GiB(94%) CN:7 DL:22MiB ETA:3s]
FILE: ../download/wsa-RP.zip
-----------------------------------------------------------------------------------------------------------

[#11a874 1.3GiB/1.3GiB(99%) CN:1 DL:16MiB]
07/16 23:00:04 [NOTICE] Download complete: ../download/wsa-RP.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0c3bd8|OK  |   3.1MiB/s|../download/Microsoft.VCLibs.140.00_x64.appx
9f444b|OK  |   1.7MiB/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
d9caa7|OK  |   904KiB/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
11a874|OK  |    21MiB/s|../download/wsa-RP.zip

Status Legend:
(OK):download completed.
Extracting WSA
unzipping WsaPackage_2311.40000.5.0_x64_Release-Nightly.msix to /tmp/wsa-build-j66X4cNgrT_/wsa
 unzipping from /tmp/wsa-build-j66X4cNgrT_/wsa/WsaPackage_2311.40000.5.0_x64_Release-Nightly.msix
done

Generating Download Links
Generating Magisk download link: release type=canary
Failed to fetch from GitHub API, fallbacking to jsdelivr...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/LSPosed/WSA-Addon/releases/latest (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generateMagiskLink.py", line 64, in <module>
    res = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/LSPosed/WSA-Addon/releases/latest (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Download Directory
```
[//]: <> (Don't modify below)
</details>

**Comment by GEOXER123** [comment]
same error as above
