### ISSUE TITLE
magisk下载    .py    拒绝访问

### ISSUE THREAD

**Issue by mon3tr** [LSPosed/MagiskOnWSALocal#81]
COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico  --root-sol magisk --compress
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1662517927&P2=404&P3=2&P4=WDp5%2f6Jg2b9wKlHW4b%2fSKGYZlPslT0hy0uFb1aqFHzWflG%2f7HBlBKq8ZHBybtEmvbZ9Lu90hRCnI%2f7k5fl7CQA%3d%3d to /usr/local/games/MagiskOnWSALocal-main/download/xaml-x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1662545546&P2=404&P3=2&P4=cugkGbRHEvezRRC7zc4zOzZzfTwdiLG5R4%2bLIRpyebp9XsgTCEh6t3YgH55Jy11FoQu4W95R1smLFHToCQQoFQ%3d%3d to /usr/local/games/MagiskOnWSALocal-main/download/wsa-x64-retail.zip
Generating Magisk download link: release type=stable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3e556f9030>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /topjohnwu/magisk-files/master/stable.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e556f9030>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/games/MagiskOnWSALocal-main/scripts/generateMagiskLink.py", line 35, in <module>
    magisk_link = json.loads(requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /topjohnwu/magisk-files/master/stable.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e556f9030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Build: an error has occurred, exit
Cleanup Download Directory

大佬求解

**Comment by Howard20181** [comment]
网络错误，挂代理
